# Use the official PostgreSQL 14 image
FROM postgres:14

# Set environment variables
ENV POSTGRES_USER=argonaut
ENV POSTGRES_PASSWORD=
ENV POSTGRES_DB=argodb

# Expose the default PostgreSQL port
EXPOSE 5432
